version: '2'

services:
  web:
    container_name: vapor_web
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"

  vapor:
    container_name: vapor_vapor
    build:
      context: ./vapor
      args:
        - INSTALL_MYSQL=true
    links:
      - web
    volumes_from:
      - data
    ports:
      - "8080:8080"

  data:
    image: tianon/true
    volumes:
      - ../:/vapor
