version: '2'

services:
  web:
    container_name: vapor_web
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"

  vapor:
    container_name: vapor_vapor
    build: ./vapor
    links:
      - web
    volumes_from:
      - data


  data:
    image: tianon/true
    volumes:
      - ../:/vapor
